name: producer-sbx
spec:
  labels:
    demo: "pubsub"
  cluster: "@{cluster}"
  forks:
  - forkOf:
      kind: Deployment
      name: producer
      namespace: pubsub-demo
  defaultRouteGroup:
    endpoints:
    - name: frontend
      target: http://frontend.pubsub-demo.svc:4000