apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: kafka-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      serviceAccountName: consumer
      enableServiceLinks: false
      containers:
        - name: consumer
          image: asia-docker.pkg.dev/itone-295207/casino-backend/signadot/kafka-demo:v61
          command:
            - "npm"
            - "run"
            - "consumer"
          env:
            # - name: CONSUMER_PORT
            #   value: "40001"
            - name: BASELINE_NAME
              value: "consumer"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 40001
          securityContext:
            # Run with the "node" user
            runAsUser: 1000
            runAsGroup: 1000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: consumer
#   namespace: kafka-demo
#   labels:
#     app: consumer
# spec:
#   type: ClusterIP
#   selector:
#     app: consumer
#   ports:
#     - port: 4001
#       targetPort: 40001
#       name: http
