apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: pubsub-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: pubsub-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      serviceAccountName: consumer
      enableServiceLinks: false
      containers:
        - name: consumer
          image: asia-docker.pkg.dev/itone-295207/casino-backend/signadot/pubsub-demo:v91
          command:
            - "npm"
            - "run"
            - "consumer"
          env:
            - name: BASELINE_NAME
              value: "consumer"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 40001
          securityContext:
            # Run with the "node" user
            runAsUser: 1000
            runAsGroup: 1000